theme: minima
title: Nate's Test Site
author: Nate Rowan
email: naterowan00@aol.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test site, yay

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
